module VizborCLI::GitIgnore
  extend self

  def modify : Nil
    path = Path.new(".gitignore")
    file : String = File.read(path)
    File.write(path, content)
  end

  private def content : String
    "*~
.directory
.DS_Store

# Generated by Crystal
/docs/
/lib/
/bin/
/.shards/
*.dwarf

# Editor directories and files
.idea
#.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
"
  end
end
