module VizborCLI::GitIgnore
  extend self

  def modify : Nil
    path = Path.new(".gitignore")
    File.write(path, content)
  end

  private def content : String
    "*~
.directory
.DS_Store

# Ignore temporary media files
/assets/media/uploads/**
!/assets/media/uploads/.gitkeep

# Generated by Crystal
/docs/
/lib/
/bin/
/.shards/
*.dwarf

# Editor directories and files
.idea
#.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
"
  end
end
