name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check code style
        run: bin/ameba
      - name: Check formatting
        run: crystal tool format --check
      - name: Run tests
        run: crystal spec
